### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Pelirrojo** [GregorUT/vgchartzScrape#6]
Hi,

I found your Kaggle dataset very interesting. I've worked on [this crawler fork](https://github.com/Machine-Learning-Labs/vgchartzScrape) to keep it up to date and operate with the latest version of the data. I also want to made a Pull Request when it will be finished.

I wanted to know if you thought about licensing the code, e.g. MIT? Since I'd like to apply it and respect your wishes about it.

Is it possible to apply MIT through generating a LICENSE.md file?

Greetings and thanks in advace for your reply.
Manuel

**Comment by JulesMillen** [comment]
Hi Pelirrojo,

This is the only way I could think to contact you - so I hope this reaches you...

I have just downloaded and tried to run your version of the vgchartzScrape.

It seems to run okay but it is only outputting 200 rows of data, most of which are missing information from most columns (this issue is occurring on multiple computers). I am not sure whether this is an issue at my end (I dont think it is, however I am extremely novice with python) or whether something has changed in the website and so the code needs to be updated?

Any help would be hugely appreciated!

Alternatively, if you happen to have a scrape of the data from when you worked on this, could I please get it from you?

Many thanks in advance,
Jules

**Comment by Pelirrojo** [comment]
Hi Jules, I had the [issues in my repository](https://github.com/Machine-Learning-Labs/vgchartzScrape/issues) closed until now.  Sorry about that. It would be better to continue the conversation there.

I opened this request to the original author to respect his preferences about a possible licensing of the code in the repository and its forks, but it gives me the impression that he doesn't receive the mails and/or doesn't maintain this repository, so I'll close it.

Thanks anyway.
